Repository E-Edu/frontend, pull requests merged in 2020-03, with the labels that each got.

#41 Added Arimo Font with Own CSS Class
  src/css/main.css
  src/css/main.min.css
  src/css/main.scss
Labels: bug, documentation

#148 Imprint Sidebar / Header update
  src/components/Header/index.js
  src/pages/Imprint/index.js
Labels: FINISHED

#149 Fixed Header Icon
  src/components/Header/index.js
Labels: BUG, FINISHED
